### ISSUE TITLE
Playbook should be able to manage multiple installs on the same platform

### ISSUE THREAD

**Issue by whitleykeith** [cloud-bulldozer/scale-ci-deploy#118]
Currently, the playbook does not have the ability to manage multiple installs on the same platform, which can lead to instability when using the same orchestration host across different workflows

The core issue is that the playbook has hardcoded directories in which it stores run specific information like terraform state metadata, kubeconfig, and openshift install logs. For instance, the playbook will always put those things at `playbook_dir/scale-ci-aws` whenever installing in AWS.

However, if you have two pipelines using the same orchestration host and also installing into AWS (i.e. PerfScale CI runs AWS and AWS OVN as separate pipelines) then this can easily start to break things, as both pipelines would be fighting over that directory and cleanups could easily remove the wrong cluster.

This could be solved if the directory was parameterized by either (1) a user/system-supplied variable or (2) a randomly generated string outputted in the playbook logs. The openshift installer does generate a unique `infraID` which I think we should add as a subdirectory underneath the platform level directory. That would mean that all related files for a run would go under `scale-ci-deploy/scale-ci-$platform/$infraID/`

**Comment by jtaleric** [comment]
I like the idea of parameterized. It could be randomly generated, like :
 
`$platform-$sdn-unix_timestamp` 

Or we could prefix the timestamp... I do like the concept, this would also help us with reusing worker nodes.

**Comment by rsevilla87** [comment]
Linking PR https://github.com/cloud-bulldozer/scale-ci-deploy/pull/126
