### ISSUE TITLE
GCP cluster cleanup fails to delete network resources due to firewalls rules unknown to cluster

### ISSUE THREAD

**Issue by qiliRedHat** [cloud-bulldozer/scale-ci-deploy#169]
**Problem**
For GCP provider, the cleanup task looped trying to delete the network for about 20 hours but never got successful. openshift_install.log has this error  `msg="failed to delete network qiliredhat-4-9-gcp-ov-tcgsh-network with error: RESOURCE_IN_USE_BY_ANOTHER_RESOURCE: The network resource 'projects/openshift-qe/global/networks/qiliredhat-4-9-gcp-ov-tcgsh-network' is already being used by 'projects/openshift-qe/global/firewalls/k8s-fw-abb7660d258204d05a6b1455ac989954'"`

I consulted installer QE team member, he replied 

> I ran the installer to destroy your cluster again and the network where the cluster resides was left behind. Installer can't destroy 2 firewall rules and it kept looping. I manually deleted the firewall rules and the installer finished destroying the cluster.
> For firewall, it usually when a node is created outside of the cluster (e.g. using a yaml file)
> Is there a way to use scale up to get your machines?
Otherwise, installer will always loop - and you have to put in magic to find those extra firewall rules.
> Machine created from yaml is not known to the cluster - when they are created, the firewalls are created so the cluster doesn't know what those firewall rules are and won't touch them.

@mohit-sheth, have you met this in dev team's GCP account? Is that possible to change the way of creating machineset? Please let me know your thought about this.

**Detail Information**
First time trying to delete network.
```
time="2021-09-08T16:51:21Z" level=debug msg="Listing networks"
time="2021-09-08T16:51:21Z" level=debug msg="Found network: qiliredhat-4-9-gcp-ov-tcgsh-network"
time="2021-09-08T16:51:21Z" level=debug msg="Listing routes"
time="2021-09-08T16:51:21Z" level=debug msg="Deleting network qiliredhat-4-9-gcp-ov-tcgsh-network"
time="2021-09-08T16:51:22Z" level=debug msg="Networks: 1 items pending"
time="2021-09-08T16:51:25Z" level=debug msg="Listing compute instances"
```
First time `failed to delete network` msg was seen.
```
time="2021-09-08T16:52:08Z" level=debug msg="Listing networks"
time="2021-09-08T16:52:09Z" level=debug msg="Found network: qiliredhat-4-9-gcp-ov-tcgsh-network"
time="2021-09-08T16:52:09Z" level=debug msg="Listing routes"
time="2021-09-08T16:52:09Z" level=debug msg="Deleting network qiliredhat-4-9-gcp-ov-tcgsh-network"
time="2021-09-08T16:52:09Z" level=debug msg="failed to delete network qiliredhat-4-9-gcp-ov-tcgsh-network with error: RESOURCE_IN_USE_BY_ANOTHER_RESOURCE: The network resource 'projects/openshift-qe/global/networks/qiliredhat-4-9-gcp-ov-tcgsh-network' is already being used by 'projects/openshift-qe/global/firewalls/k8s-fw-abb7660d258204d05a6b1455ac989954'"
time="2021-09-08T16:52:09Z" level=debug msg="Networks: 1 items pending"
time="2021-09-08T16:52:15Z" level=debug msg="Listing compute instances"
```
The cleanup task looped trying to delete the network for about 20 hours but never got successful.
```
time="2021-09-09T12:32:48Z" level=debug msg="Listing networks"
time="2021-09-09T12:32:49Z" level=debug msg="Found network: qiliredhat-4-9-gcp-ov-tcgsh-network"
time="2021-09-09T12:32:49Z" level=debug msg="Listing routes"
time="2021-09-09T12:32:49Z" level=debug msg="Deleting network qiliredhat-4-9-gcp-ov-tcgsh-network"
time="2021-09-09T12:32:49Z" level=debug msg="failed to delete network qiliredhat-4-9-gcp-ov-tcgsh-network with error: RESOURCE_IN_USE_BY_ANOTHER_RESOURCE: The network resource 'projects/openshift-qe/global/networks/qiliredhat-4-9-gcp-ov-tcgsh-network' is already being used by 'projects/openshift-qe/global/firewalls/k8s-fw-abb7660d258204d05a6b1455ac989954'"
time="2021-09-09T12:32:49Z" level=debug msg="Networks: 1 items pending"
```

**Comment by qiliRedHat** [comment]
@mohit-sheth PTAL
@kedark3 FYI

**Comment by kedark3** [comment]
@mohit-sheth as you are more familiar with the scale-ci-deploy - is it possible for us to add some of the networking/firewall cleanup tasks before we call destroy cluster ?

**Comment by qiliRedHat** [comment]
https://github.com/cloud-bulldozer/scale-ci-deploy/pull/173 is trying to fix this.

**Comment by qiliRedHat** [comment]
I verified the cleanup can clear the firewall resources now, though there are still 2 firewall resources that do not start with cluster-name, as the 2 selected items shown in the below screenshots. Cleanup task does not loop and wait anymore.
<img width="847" alt="Screen Shot 2021-09-16 at 4 40 25 PM" src="https://user-images.githubusercontent.com/81630527/133751001-95f04558-99cf-45ed-a0f3-de5457a0e0cb.png">
