### ISSUE TITLE
Add cluster_name to infra and worklaod machineset to identify resources

### ISSUE THREAD

**Issue by qiliRedHat** [cloud-bulldozer/scale-ci-deploy#170]
This is an better to have request to make the work of GCP resource admin easier. QE team's GCP resource admin found some disk resources reached the quota limit, they found some disk instances with name prefix of `infra-` and `workload-` but could not tell know whom the resources belong to, that increased the time of communication and fix of resource problem.

After consulting @kedark3, he suggest to add cluster name into the name of infra and workload machineset.

**Comment by qiliRedHat** [comment]
@mohit-sheth I opened pr https://github.com/cloud-bulldozer/scale-ci-deploy/pull/171, please review.

**Comment by kedark3** [comment]
Thank you @qiliRedHat for taking a quick look at this.

**Comment by qiliRedHat** [comment]
Talked with @mohit-sheth, he explained why the cluster name is not in the machinset.

we initially removed the cluster name from the machineset bc if the cluster name is long enough the machineset name exceeds the length and openshift won't create it

He made a change to fix the disks that are hanging around even after cleanup #172

As #172 already addressed the storage deletion issue, there won't be infra or workload storage resource left, and considering #172 will bring back the risk of 'machineset name exceeds the length', I think #172 is a better solution for this issue.

Close this issue now, if the problem is seen again after #172 merged, I will reopen it.

**Comment by qiliRedHat** [comment]
Talked to To Huang in QE team -export for GCP and installer,  and then talked with @mohit-sheth, #171 fix is supposed to fix the firewall issue as well. So we decided to take it. I'll keep an eye on long-cluster name issue.

**Comment by qiliRedHat** [comment]
https://github.com/cloud-bulldozer/scale-ci-deploy/pull/173

**Comment by qiliRedHat** [comment]
Now the infra disk resource and workload disk resource all have cluster-name as the prefix. And I verified they can be deleted from GCP Console after the cleanup task is run.
qiliredhat-4-9-gcp-ad-pzznn-infra-a-srgf7
qiliredhat-4-9-gcp-ad-pzznn-workload-a-62ndw
